export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_OUT = 'AUTH/SIGN_OUT';
export const CURRENT_USER = 'AUTH/CURRENT_USER';
export const USER_NOT_EXIST = 'AUTH/USER_NOT_EXIST';

export const NEXT_STEP = 'APP/NEXT_STEP';
export const RESTART = 'APP/RESTART';
export const SHOW_CONFIRMATION = 'APP/SHOW_CONFIRMATION';
export const HIDE_CONFIRMATION = 'APP/HIDE_CONFIRMATION';

export const ADD_POST = 'POST/ADD_POST';
export const UPDATE_POST = 'POST/UPDATE_POST';

export const ADD_COMMENT = 'POST/ADD_COMMENT';
export const UPDATE_COMMENT = 'POST/UPDATE_COMMENT';