export const NEXT_STEP = 'APP/NEXT_STEP';
export const RESTART = 'APP/RESTART';
export const CLEAR_DATA = 'APP/CLEAR_DATA';
export const SHOW_CONFIRMATION = 'APP/SHOW_CONFIRMATION';
export const HIDE_CONFIRMATION = 'APP/HIDE_CONFIRMATION';